export const  GET_COUNTRIES = "GET_COUNTRIES";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const GET_COUNTRIE_BY_NAME ="GET_COUNTRIE_BY_NAME";
export const CHANGE_PAGE =  "CHANGE_PAGE";
export const FILTER_COUNTRY_CONTINENT = "FILTER_COUNTRY_CONTINENT";
export const GET_COUNTRIES_BY_ID = "GET_COUNTRIES_BY_ID";
export const GET_ACTIVITYS= "GET_ACTIVITYS";
export const COUNTRY_SELECT = "COUNTRY_SELECT";
export const FILTER_COUNTRY ="FILTER_COUNTRY"

